project:
  type: website

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Introduction"
      - href: data_analysis.qmd
        text: "Data Cleaning & Exploration"
      - href: eda.qmd
        text: "Exploratory Data Analysis"
      - href: skill_gap_analysis.qmd
        text: "Skill Gap Analysis"
      - href: ml_methods.qmd
        text: "ML Methods"
      - href: nlp_methods.qmd
        text: "NLP Methods"
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/CYXNBNBNB/ad688-employability-sp25A1-group6.git

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



